site_name: RADTorch

theme:
  name: material
  custom_dir: docs/home/
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: cyan
      accent: cyan
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: cyan
      accent: cyan

  icon:
    repo: fontawesome/brands/github
    logo: material/book
    logo: material/cube-scan

  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.tabs
    # - navigation.indexes

  extra:
    version:
      provider: mike


edit_uri: ""

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  # - pymdownx.tabbed:
  #     alternate_style: true
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
          heading_level: 2
          show_signature: true
          separate_signature: true
          show_source: false

          show_root_heading: true
          show_root_toc_entry: false
          show_root_full_path: false
          show_object_full_path: false
          show_root_members_full_path: false
          show_category_heading: true


        selection:
          filters:
            - "!^_"  # exlude all members starting with _



repo_url: https://github.com/radtorch/radtorch
repo_name: radtorch/radtorch

extra_css:
  - 'stylesheets/extra.css'
  - https://unpkg.com/mermaid@8.8.0/dist/mermaid.css
#
extra_javascript:
  - https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js

# https://unpkg.com/browse/mermaid@8.8.0/

nav:
    - RADTorch : 'index.md'
    - About : 'about.md'
    - Getting Started: 'start.md'
    - Documentation:
        - 'data.md'
        - 'model.md'
        - 'classifier.md'
        - 'extractor.md'
        - 'inference.md'
        - 'metrics.md'
    - Information:
        - 'version.md'
        - 'copyrights.md'
    - Help: 'support.md'
